import StatCard from '@/components/dashboard/StatCard';
import AreaChartCard from '@/components/dashboard/AreaChartCard';
import RecentTable from '@/components/dashboard/RecentTable';
import ActivityFeed from '@/components/dashboard/ActivityFeed';

const chartData = [
  { name: 'Mon', value: 120 },
  { name: 'Tue', value: 200 },
  { name: 'Wed', value: 150 },
  { name: 'Thu', value: 260 },
  { name: 'Fri', value: 180 },
  { name: 'Sat', value: 300 },
  { name: 'Sun', value: 240 },
];

const tableRows = [
  { id: '1', name: 'Invoice #1024', amount: '$1,250.00', status: 'Paid' as const, date: '2025-09-04' },
  { id: '2', name: 'Invoice #1025', amount: '$980.00', status: 'Pending' as const, date: '2025-09-05' },
  { id: '3', name: 'Invoice #1026', amount: '$410.00', status: 'Failed' as const, date: '2025-09-06' },
  { id: '4', name: 'Invoice #1027', amount: '$2,040.00', status: 'Paid' as const, date: '2025-09-07' },
];

const feedItems = [
  { id: 'a', text: 'New user registered: alex@example.com', time: '2 hours ago' },
  { id: 'b', text: 'Payment received: $2,040.00', time: '4 hours ago' },
  { id: 'c', text: 'API key regenerated by admin', time: '1 day ago' },
];

export default function Dashboard() {
  return (
    <div className='flex flex-col gap-6'>
      <div className='grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4'>
        <StatCard title='Revenue' value='$12,340' delta='+5.4% vs last week' />
        <StatCard title='Active Users' value='1,284' delta='+2.1% vs last week' />
        <StatCard title='Transactions' value='542' delta='-1.2% vs last week' />
        <StatCard title='Conversion' value='3.8%' delta='+0.3% vs last week' />
      </div>

      <div className='grid grid-cols-1 gap-6 xl:grid-cols-3'>
        <div className='xl:col-span-2'>
          <AreaChartCard title='Weekly Performance' data={chartData} />
        </div>
        <ActivityFeed title='Recent Activity' items={feedItems} />
      </div>

      <RecentTable title='Latest Invoices' rows={tableRows} />
    </div>
  );
}
